name: ci

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@main
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run typecheck
      - run: pnpm run lint
