name: ci

on:
  push:
    branches:
      - "**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@main
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run format

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@main
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint
